name: Release
on:
  push:
    tags:
      - '*'
  release:
    type: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - run: flutter config --enable-linux-desktop

      - name: Patch for linux build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt install libavcodec-dev libavformat-dev libavdevice-dev
          sudo apt-get install libsdl2-dev
          flutter doctor

      - name: Build APP
        run: flutter build linux

      - name: Bundle deb
        run: ./dist/linux_deb.sh

      - name: upload release artifact.
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/quiet_amd64.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
